---

- name: Leave cluster if already joined
  shell: docker swarm leave --force
- name: Join manager
  shell: >
    docker swarm join
    --token={{ swarm_manager_token.stdout }}
    {{ boostrap_node_ip.stdout }}:2377
