---

- name: Retrieve join tokens
  become: yes
  hosts: bootstrap_node
  roles:
    - role: get-join-token

- name: Join cluster
  become: yes
  hosts:
    - node2
    - node3
  roles:
    - role: join-cluster

- name: Deploy services
  become: yes
  hosts: bootstrap_node
  roles:
    - role: deploy-services

