---

- name: Init swarm
  shell: docker swarm init --advertise-addr {{ ansible_ssh_host }} || true
- name: Get join token
  shell: docker swarm join-token -q manager
  register: swarm_manager_token
- name: Register bootstrap node ip
  shell: ifconfig | grep inet | awk '{print $2}' | grep 192
  register: boostrap_node_ip
